### ISSUE TITLE
Add Internationalization to Export

### ISSUE THREAD

**Issue by brandondove** [WebDevStudios/custom-post-type-ui#150]
When you export code for the CPT, the labels should be wrapped in __(), _x() depending on their gettext context.

**Comment by tw2113** [comment]
As is, the "get code" functionality depends on the settings provided by the user, and in the dev branch here on github, I have it not providing non-set labels, so that it falls to default values provided by WordPress core. Unless I'm mistaken, that eliminates issue because the default string values would be handled by WP core, and the provided values would already be translated by the user. Let me know if I'm mistaken and I'll re-open the issue.
