### ISSUE TITLE
Notice: Undefined index: rewrite_withfront in custom-post-type-ui.php on line 100

### ISSUE THREAD

**Issue by shampine** [WebDevStudios/custom-post-type-ui#170]
The plugin from WordPress.org throws this error through admin with debugging enabled.

I see that the GitHub version has ternary reversed and set to isset. Isset does fix it. Opening the issue because while I haven't tested the GitHub code, if that works, the wordpress.org version needs updating.

**Comment by chickwithbob** [comment]
This really needs to get fixed. Uninstalling and getting rid of this plugin on a lot of sites that it is now affecting

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/custom-post-type-ui/issues/275

They were simple notices that weren't having any negative effect. Once WP_DEBUG is disabled, they wouldn't even show up. I fixed it at one point, but then had to remove it again because unintended logic was executing thanks to string '0' evaluating to true for the empty() check. This was a way that the settings were saved in the pre-1.0.x version, and I store string "true" and "false"  in the new settings, which will keep me a bit sane in this department.

**Comment by chickwithbob** [comment]
The problem is that if sites have errors, there is a lot of extra 'noise' being generated making it more difficult to debug

**Comment by tw2113** [comment]
If you really insist, I can tell you how to get the errors cleared out for your own installs, and even provide the copy of the file to use for it.

**Comment by chickwithbob** [comment]
Hi there, I know how to clear the errors. There are so many plugins that exhibit these sorts of errors it just gets frustrating... no problem anyway. I know none of us have time supporting stuff for free :)

**Comment by tw2113** [comment]
For what it's worth, I kept on it for all the other areas of the plugin, whenever I could.
