### ISSUE TITLE
CPTUI's UI Feedback

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#225]
https://wordpress.org/support/topic/aweful-new-user-interface?replies=3#post-6551814

"i really appreciate every update and work you spent in this project. really. CPT UI is one of my must have plugins in every wp project. but this new 1.0 update went into the wrong direction. before its interface was clearly arranged and now i have to make three clicks to edit a label. also it does not feel "wordpress like". so it does not fit well in wp environment. please go back to the roots – thank you!"

"benefits of old interface:
with one click you get to an overview where you see your CPTs AND also "system"-CPTs generated by other plugins <- very useful
(now i need 5 clicks to find my CPT)
also now there seems to be no table where i can see all CPTs and its settings. i think i don't have to describe you what i mean.
the simplicity of custom CPT was the big advantage! now everything is nested.

hope this helps"

**Comment by rpkoller** [comment]
+1 i will give it a bit of a thought when i am done with the refining of the translation draft.

**Comment by tw2113** [comment]
https://wordpress.org/support/topic/incoming-version-102?replies=9#post-6560538

"I have to say I'm not a big fan of the UX/UI change. The previous version's presentation for listing out custom post types/taxonomies was more comparable to a basic WordPress interface and, therefore, more familiar and comprehensible. The accordion functionality of the labels/settings fields feels a little clumsy, too, and doesn't fit well on smaller screens.

Friendly suggestion: make the UX/UI look and feel just the default interface for pages/posts. In other words, just have them list out in the same fashion with an "Add New" button next to the section title. That way you don't have to teach folks how to use a new interface."

**Comment by rpkoller** [comment]
A few thoughts. Generally i have to agree with the first post. A downside of the new layout is that you need more clicks to reach your goals. Visually the layout is a bit "naked" and the fields don't line up on each side. You have to expand settings, labels and starter notes and you are only able to have one field open at time. An expanded field has only a limited fixed height with some sort of shadow halos at the upper and lower end which isn't very comforting. The limited height leads also to a lot of empty and unused screen space beneath on a 27" monitor. A few ideas in no particular order to fire up the discussion. 

- Add more submenus in the admin side bar. Create separate submenus for post types and taxonomies.  add post type, edit post type, add taxonomy, edit taxonomy. Why? At the moment you have to click the post type submenu. per default you get to the new post type tab. from there you have to click edit post type. then you have to choose the select field which post type you wanna edit. quite a few clicks. by extending the number of submenus you could jump directly to the edit post type e.g. 

- next the general post type /taxonomy layout. at first i would use meta boxes to group sections ( like in media or in the advanced custom fields plugin - the latter takes extensive use of grouping content in those interface elements). i would drop the expand pattern and show everything whats there all the time. the first block with slug, label and description for the post types with a width of 100%. in the case of taxonomies i would display the slug and labels also with a width of 100% but beneath the attach post type check box in a two column layout. then it isn't a long packed vertical slug. 
next i would display the fields of labels in a width of 50% column and the settings next to it also in a width of 50% column. beneath the starter notes again a width of 100%. You would get a well layed out form showing all possibilities at once and which is easily accessible and graspable. 

- the layout for edit post types and taxonomies could be the same; the only difference it is without the starter notes. 

- the selection which post types or taxonomies you have and which to edit. the select field is a bit unflattering. I might have a crazy idea. a pattern advanced custom fields is using for their field groups. a list view which expands the settings to adjust when clicked. guess its heavy on jquery. but at least it might be a midway between the old schema of an old fashined list view and the new select field. in the following video it is used for editing the field groups. 

https://dl.dropboxusercontent.com/u/8578/acf.mov

imagine you have a list view of registered post types and taxonomies. if you click one post type or taxonomy the item expands and shows the layout of available fields. instead of the close field button you could place a save post type/taxonomy button. On a side note you can also see the already mentioned point about the the acf plugins ui. It has a clean, compact, not naked look, by their usage of meta boxes to group their content. 

- i would also drop the expand pattern in the help section. just use three meta boxes to group and visually seperate the three question types. and show of questions and answers at once. 

Well that's it for now with a few initial suggestions. Any thoughts? ;)

**Comment by tw2113** [comment]
https://wordpress.org/support/topic/incoming-version-102?replies=13#post-6561791

The analogy to Advanced Custom Fields was a good one. ACF does a great job of handling a complicated data set in a comprehensive way. Also, the listing of custom fields behaves just like the WordPress pages/posts sections with the familiar group of edit/duplicate/trash buttons for each listing (no UX learning curve!).

One last thing: the import/export functionality of ACF is pretty straight forward, too. On the export screen, you just choose via checkboxes the fields you want to export and hit a "Download" button. The import screen is just uploading the exported file. Voila!

Anyway, I hope this is helpful info. Happy coding!
Mark

**Comment by tw2113** [comment]
This is just a first pass comment based on the feedback above.

Things I need to work on:
--Fewer clicking. This includes getting to a point of being able to edit something, as well as display of editable things.
--Less hiding of things for the sake of screen space. I see comments about difficult to use on smaller screens, and wasted space on larger screens. Finding a middle ground may prove interesting.

Things to investigate:
--How other post type creation plugins have handled UI and see what I can borrow/gain from their own experiences.

**Comment by tw2113** [comment]
"The UI changes made it so hard to access existing post types and to modify them.

- We no global view over all post types and taxonomies.
- Now we need 5 clicks to edit an existing post type, it is wrong :)
- Tabs (Add New/Edit ) aren't necessary and is a waste of time.
- The dropdown menu to select post types is not better than a simple list with "edit, delete, add" boutons direct on it.
- The accordion menus for labels and settings are way worse than simple inline sections where you can just scroll down and see everything quite fast.

I know you are trying to make improvements but this is a quite common mistake designing interfaces. For this kind of plugin and amount of data you don't need to organize the content with dropdown menus, tabs and accordions, it is a waste of time and bad UX.
Just keep it simple and easily accessible.

Anyway, thanks for the reply.
Cheers."

**Comment by tw2113** [comment]
**Things in the works or already ready:**

Removed needing to click "select" when editing post types or taxonomies. You will be switched automatically upon selection. Clicks removed: 1.

Removed blank value in select dropdown of registered post types or taxonomies. You will have the first one auto-selected upon initial page load. Clicks removed: 1.

Removing accordion effect in general. Clicks removed: 42,000.*

**Things being mentally debated:**

Moving the "Edit ___" Tab to the front of the list of tabs and have it be default selected when clicking via Admin menu.

*May be exaggerated

**Comment by tw2113** [comment]
Removing the 1.1 milestone not because I consider this fixed, but because it's a topic that will likely be ongoing for an unknown length of time. There's always UI revisions to be made.

**Comment by tw2113** [comment]
Many of the complaints seem to have died down or they're just not being brought up any more.
