### ISSUE TITLE
Uniformization of headings and help texts

### ISSUE THREAD

**Issue by pedro-mendonca** [WebDevStudios/custom-post-type-ui#272]
A lot of headings and help texts from post types and taxonomies can be uniformized to simplify translation of plugin.

Fields order should also be reviewed.

In which branch would you like this to be done?

**Comment by tw2113** [comment]
You would want to make any PRs against the 1.1 branch.

**Comment by tw2113** [comment]
Any thoughts at the moment regarding this? Getting to the point where this is one of the few remaining todos left.

**Comment by pedro-mendonca** [comment]
Yes, as I've suggested before, I think there are some fields in CPT and Taxonomies that are mostly the same, and in some cases they have different description or help text. This is a bit uncoherent and mostly is redundant translation work for translators. For this, it would be great to fully review and compare both CPT and Taxonomy fields.

The plugin would also benefit of a review of fields order, some that depend on other fields being *True* might be placed below it's parent, and eventually the field might be disabled if it's parent isn't *True*.

**Comment by tw2113** [comment]
The more I think about this one, the more I think the topic should go in the other direction. They should be separated out more and more relative to the actual setting involved, instead of consolidated to save on a bit of typing for translators, bless their hearts.

Depending on feedback I get, I may put off the help text reworking for a future version, probably 1.2.0, so that I can get 1.1.0 out the door and get the revised UI/click amount out the door, as well as the other new features that are pending.

**Comment by pedro-mendonca** [comment]
Ok, I've suggest this because help texts had some issues, errors etc.
Whatever review direction you go is a good one.
Keep up the good work :+1:
