### ISSUE TITLE
PHP Notices since 1.0.6 update

### ISSUE THREAD

**Issue by emzo** [WebDevStudios/custom-post-type-ui#275]
After updating to 1.0.6 I'm getting lots of `Undefined index` PHP warnings in my log file. Here's a few...

```
[15-Apr-2015 09:54:53 UTC] PHP Notice:  Undefined index: rewrite_withfront in /srv/www/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 168
[15-Apr-2015 09:54:53 UTC] PHP Notice:  Undefined index: rewrite_hierarchical in /srv/www/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 266
[15-Apr-2015 09:58:03 UTC] PHP Notice:  Undefined index: exclude_from_search in /srv/www/wp-content/plugins/custom-post-type-ui/inc/post-types.php on line 425
```

**Comment by hansott** [comment]
+ 1

**Comment by hansott** [comment]
@emzo https://wordpress.org/support/topic/problem-with-rewrite-with-front-after-update-from-085-to-105

**Comment by tw2113** [comment]
Stuff I'm going to have to live with for the time being, because string "0" evaluates to false when used in php's empty() function. It's not going to do you any harm, and it may even clear up if you simply re-save your post type/taxonomy settings, since I cast those to "false" or "true" upon save instead of "1" and "0"

**Comment by hansott** [comment]
@tw2113 Thanks for the info.

**Comment by marty118** [comment]
I have similar warnings:

Notice: Undefined index: rewrite_withfront in /mnt/stor3-wc2-dfw1/481124/www.meshagencytest.com/web/content/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 265

Notice: Undefined index: rewrite_hierarchical in /mnt/stor3-wc2-dfw1/481124/www.meshagencytest.com/web/content/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 266

Notice: Undefined index: rewrite_withfront in /mnt/stor3-wc2-dfw1/481124/www.meshagencytest.com/web/content/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 265

Notice: Undefined index: rewrite_hierarchical in /mnt/stor3-wc2-dfw1/481124/www.meshagencytest.com/web/content/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 266

**Comment by tw2113** [comment]
And they are not hurting anything nor will they interfere with the functionality, but it's something i'm having to do since empty( '0' ) evaluates to true, and '0' is one of the values possibly stored in the old settings. New settings store 'true' or 'false' which is less of an issue with the conversion.

**Comment by danielepennati** [comment]
To fix the php notice is enough to change line 265 and 266 from
```
$rewrite['with_front'] = ( 'false' === disp_boolean( $taxonomy['rewrite_withfront'] ) ) ? false : true;
$rewrite['hierarchical'] = ( 'true' === disp_boolean( $taxonomy['rewrite_hierarchical'] ) ) ? true : false;
```
to
```
$rewrite['with_front'] = ( !isset($taxonomy['rewrite_withfront']) || 'false' === disp_boolean( $taxonomy['rewrite_withfront'] ) ) ? false : true;
$rewrite['hierarchical'] = ( isset($taxonomy['rewrite_hierarchical']) && 'true' === disp_boolean( $taxonomy['rewrite_hierarchical'] ) ) ? true : false;
```

**Comment by tw2113** [comment]
Does that take into account how string zero evaluates? That was the biggest issue thanks to the old settings storing its stuff like that and messing with some logic.

**Comment by danielepennati** [comment]
the php notice are about the attempt to access an unset array index:
Undefined index: rewrite_withfront
I just add a check on the existence of that index in the array: if it is set than is also evaluated the disp_bolean condition. I don't evaluate the value of the array index but only the existence.
If the index is not set the condictional control act exactly as expected

**Comment by tw2113** [comment]
I know what the errors are about, I tried fixing it at one point but the boolean logic was getting messed up because of what was being evaluated as true vs false in of my attempt to prevent the notices.

The notices aren't going to detrimental to anything, and I think would also go away with a simple edit->save of post types/taxonomies without changing settings. I save my values to "true" and "false" strings.

**Comment by tw2113** [comment]
Anyone still paying attention and experiencing these notices from time to time, can you test the alpha branch as of this evening?

We discussed it internally that we will try a go at preventing the notices, without breaking functionality.

**Comment by webcraft** [comment]
Hi, I can confirm I did have the issue, and it went away when using the alpha branch. Thanks for the fix.

**Comment by tw2113** [comment]
@webcraft did you end up re-saving the post type(s) or taxonomy(s) afterwards? or did you simply switch to the alpha version and it went away with just that?

Any breakage on the frontend where it's most important?

**Comment by webcraft** [comment]
No re-saving required. Just switching fixed it.
No breakage as on the frontend as far as I can see.

**Comment by tw2113** [comment]
Gonna mark as closed since it's in alpha from August 22nd. We shall deal with consequences from those on below 1.0.0 when the time comes.
