### ISSUE TITLE
Import process (hook data)

### ISSUE THREAD

**Issue by mentorgh** [WebDevStudios/custom-post-type-ui#289]
Hey there,

I've been using your plugin on one of my theme,
and will use it on every next one.

Usually I pack it on my theme and set on bundle with TGM class.

There is just one thing I'd suggest to get on,
could you possibly create a simple hook where I could place the export data? And then CPT UI would load it for beginner users and they'd just hit the Import button?

Currently when I bundle up your plugin, and I place the json between import textarea manually. But would be nice to have an action hook to set the import data to simplify the import process.

Keep the good work up :D

**Comment by tw2113** [comment]
Let me know if this is going to be what you need at all.

I'm thinking of adding 2 filters, like so, right before the second if statement inside of cptui_import_types_taxes_settings() so that someone could overwrite the data to use.

```
$third_party_post_type_data = apply_filters( 'cptui_third_party_post_type_import', false );
$third_party_taxonomy_data = apply_filters( 'cptui_third_party_taxonomy_import', false );
```

By default, it'd be a false value. However, if value is provided, it'll run with that data instead.

I also need to make sure that you'd only have the filtering applied for your data, once the user has clicked "import" or if it is somehow wired to only run once. The potential problem I'm seeing is having the add_filter provided data being imported and run every time the user visits the Import/Export settings page. No need to do that so frequently.

**Comment by mentorgh** [comment]
Well that's great, it would be more than enough :dancer:.

The way I did was this: Check weather a custom post type exists (which is on import data), if it doesn't exist I applied the import data to input. So theme authors can simply check if one of their cpt does not exist then they can apply the filters otherwise it would skip.

if( !post_type_exists($post_type) ) apply_filters( 'cptui_third_party_post_type_import', false );

**Comment by tw2113** [comment]
It's in my local branch now, but has not been pushed to the repo quite yet due to wifi restrictions where I presently am :)

**Comment by tw2113** [comment]
If you could please, test a copy of the current 1.2 branch to see if it meets your needs. Want to make sure this works for you before the official launch.

Thanks.

**Comment by tw2113** [comment]
Hey @mentorgh have you had a chance to test this one out yet? Would love to be able to mark this issue closed.

**Comment by tw2113** [comment]
Gonna close this. We can address issues later on. I don't promote the hooks too heavily.
