### ISSUE TITLE
Problem unserializing data

### ISSUE THREAD

**Issue by kennyr** [WebDevStudios/custom-post-type-ui#301]
**Abstract:**  I cloned a site manually. The new cloned site does not see any of the custom post types. I confirmed that the data is in the options table. The call to `get_options()` in function `cptui_create_custom_post_types()` is returning false.

I happened to come across the following information, and when I manually retrieved the serialized option data and ran it through the `maybe_unserialize()` function, it returned false.

I believe this is the cause of the failure I am experiencing.

Taken from : http://scotty-t.com/2012/03/21/ep-1-wordpress-things-you-should-never-do/

>serialize
>
>I am going to dare you to name me a good reason to create serialized arrays in your code. Since you can’t find one, I am going to ask you how great of an idea it is to store serialized arrays in the database. Since you don’t know the answer, I am going to ask you how knowledgable you are about ASCII, UTF-*, and ISO-*. Since you have no clue why I am asking you that, I want you to heed my warning: DO NOT USE SERIALIZED ARRAYS. If you do use serialized arrays, store NUMBERS and CHARs only. DO NOT STORE STRINGS of any length that constitute any amount of whitespace.
>
>Here’s why:
>
>Serialized arrays that contain strings bind those strings to their string length, making them as non-portable as possible. If you import / export data and have ANY weird characters that were pasted in from Word or worse, your strings may become invisibly altered and won’t match your bound string lengths. This is super important because of the way we get our data into a usable format when it is stored this way is through unserialize. unserialize fails easy and often when dealing with weird strings.
>
>In WordPress, maybe_unserialize is a function invoked to do this to strings stored in the wp_*meta tables. maybe_unserialize will fail as well, easily and often, but does so….SILENTLY.

Here’s what I did to test:

```php
function cptui_create_custom_post_types() {
global $wpdb;
$query = 'SELECT * FROM wp_options WHERE option_name = "cptui_post_types"';
$result = $wpdb->get_results($query);
var_dump($result[0]->option_value);
var_dump(maybe_unserialize($result[0]->option_value));
.
.
.
```
The first var_dump is showing good data retrieved from db.
The second var_dump is showing “false”.

**Comment by tw2113** [comment]
Could you elaborate on what the actual bug is, in your opinion? Or is it just the fact that we used serialization as  whole?

I ran the same test that you have above and the first one gave the serialized string back, and the 2nd one gave me an array of values. Chances are more that there is something in your settings that is causing it to have issues and not unserialize correctly.

If you could paste your values from the first var_dump I could look it over, or if you want to do an export on the post type via the plugin, I could import that into my own and look things over from there.

**Comment by kennyr** [comment]
To get this failure, I had first done a backup and restore to a new site. The article I read says that when moving data from one server to another like that, serialization can fail silently. If you can do a restore to another server like I did, and test it that way, we can see if this can be duplicated. I posted because it makes sense that this would be the cause, since that article describes the exact issue I had. 

Even if this is only an occasional issue, as serialization may or may not fail across backup/restore situations, it might be a good idea to consider using a custom table to store the data, rather than the options table. That way it can never happen for that reason. 

Unfortunately I won't be able to provide the vardump for you because I've already disabled the plugin and coded the custom post types into a class for the project I'm working on.

**Comment by tw2113** [comment]
Gotcha.

Couple thoughts for a followup. The values are likely still in the database, since we don't delete them, even upon uninstall. We may in the future, but We take up a whole 2 option rows, so I think our footprint is pretty small. 4 rows if you came from the 0.9.x version. Smaller than we would if we went the route of a custom table.

I will state that I am not sure what happened in your case, especially since I can't think of anything that would change, string-length wise in the option when moving between databases. We don't store the domain ever, for example. So what occurred remains a mystery at the moment.

Regardless, I do appreciate you taking the time to discuss the topic and seek out elaboration on why things were done the way they were.

**Comment by kennyr** [comment]
No problem Michael. I admit that mine is a bit of an edge case, but I wanted to bring it to your attention. It took me some time to track down where the failure was occurring. I saw that the data was still in the option table, so I needed to figure out why it wasn’t coming back with the function call. If I hadn’t found that article, I wouldn’t have figured it out. But what he says makes sense, so although it’s heavier, I’d go with a separate table solution to avoid the possibility of a problem with deserializing data that’s been migrated to another db.  :o)

**Comment by tw2113** [comment]
I do have to wonder if there was somehow some invalid characters and such that got saved in the data and that caused the failure.

That said, it's nowhere near a common issue, and I think it's safe to close. If it somehow comes back, we'll re-address at that time.
