### ISSUE TITLE
errors in debug log. 

### ISSUE THREAD

**Issue by karenratte** [WebDevStudios/custom-post-type-ui#338]
while researching some other problem the debug log came up with these errors. Can you explain what this might be? 

Notice: Undefined index: rewrite_withfront in ...testingsite.southernarizonaguide.com/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 284

Notice: Undefined index: rewrite_hierarchical in ...testingsite.southernarizonaguide.com/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 285

**Comment by tw2113** [comment]
See: #275 
In short, due to previously using "0" and "1" for boolean values, I can not accurately check for empty() without causing other issues with settings, thus those couple spots need to be left in. It's nothing that will take down your site or cause issues due to being present. They are simply notices.

If I ever get everyone past version 1.0.0 and off the old stored settings, I'll be able to make the amends, but until then they'll have to remain.
