### ISSUE TITLE
Upgrading to latest against 4.3.1 causes 404 errors

### ISSUE THREAD

**Issue by brandonsavage** [WebDevStudios/custom-post-type-ui#344]
I upgraded the plugin against 4.3.1 and I ended up getting 404 errors from WordPress. It no longer found my custom post types.

I'm a fairly skilled developer but new at WordPress plugin development, so please let me know what info you'd like to see to help figure out the cause of this issue. Thanks!

**Comment by brandonsavage** [comment]
I upgraded from 0.8.2 to 1.1.2.

**Comment by tw2113** [comment]
Refresh your permalinks. Just visit the settings page for it, hit save, and they should return.

**Comment by tw2113** [comment]
For what it's worth, I do recognize you and even have your Mastering OOP ebook ;)

**Comment by brandonsavage** [comment]
Thanks! That totally solved the issue! Did you enjoy the book? I may be great at OO but I'm lousy at WordPress plugins, so I appreciate the help!

**Comment by tw2113** [comment]
I did, I should probably re-read it for refresher/hardening of the knowledge though.

Regarding the 404 part, in case you're curious, it's because with the 1.0.0 release, I switched the the option table keys for our settings, to better "namespace" the plugin in the options table, as well as store each post type/taxonomy in a more scale-able way.

However, that's caused need to flush rewrite rules after the update, as you found out. Anyways, glad it was solved easily. Have a good rest of the day.
