### ISSUE TITLE
Support for the WordPress REST API?

### ISSUE THREAD

**Issue by yooakim** [WebDevStudios/custom-post-type-ui#370]
Do you have any plans to add suport for custom post types to the [WordPress REST API](http://v2.wp-api.org/)? 

As far as I understand custom post types needs to be [added specifically to be visible via the API](http://v2.wp-api.org/extending/custom-content-types/)? If this plug-in could handle this it would be superb!

[Here's](http://scottbolinger.com/custom-post-types-wp-api-v2/) some more relevant information 

Cheers,
Joakim

**Comment by tw2113** [comment]
Yes, the 1.2.0 branch already has REST API options in it to help make them compatible. Scott Bolinger is actually the one that made the initial PRs as well. I just haven't finished the rest of the items for 1.2.0 yet to get it to a point of releasing.

If you need/want to add those now, check the main custom-post-type-ui.php file to get the filter I have on the arguments right before the registration, and you can get those REST API params added now. Shouldn't break things once 1.2.0 but you'd want to change things up if you want the values saved as part of the plugin's saved options instead of done via filter.

Thanks for the interest :)
