### ISSUE TITLE
Add new labels to unit tests

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#423]
Want to make sure we're getting good coverage.

**Comment by GaryJones** [comment]
Which labels? Added to which unit tests?

**Comment by tw2113** [comment]
You'll find half of the issues are just personal notes, not conductive to outside contributions :P It would new CPT/Taxonomy labels added in recent-ish versions

**Comment by GaryJones** [comment]
For future contributors, who don't want to go a'hunting:
- [Test for CPT labels](https://github.com/WebDevStudios/custom-post-type-ui/blob/86f99e6644d32b641158ad246cd984295b836ae3/tests/CPTUI-Utilities-Test.php#L71) - see https://developer.wordpress.org/reference/functions/get_post_type_labels/ for the up-to-date list of post type labels.
- [Test for CTax labels](https://github.com/WebDevStudios/custom-post-type-ui/blob/86f99e6644d32b641158ad246cd984295b836ae3/tests/CPTUI-Utilities-Test.php#L125) - see https://developer.wordpress.org/reference/functions/get_taxonomy_labels/ for up-to-date list of taxonomy labels.

Suggestion: Add a `@since` tag to each test DocBlock to say up to which version of WP the labels now cover. i.e.

```php
/**
 * Tests for our registered labels for the post type.
 *
 * @since 0.9.0
 * @since 1.6.0 Added the `featured_image`, `set_featured_image`, `remove_featured_image`
 *              and `use_featured_image` labels (all WP 4.3.0).
 *              Added `the archives`, `insert_into_item`, `uploaded_to_this_item`, `filter_items_list`, 
 *              `items_list_navigation`, and `items_list` labels (all WP 4.4.0).
 *              Added the `view_items` and `attributes` labels (both WP 4.7.0).
 */
```

```php
/**
 * Tests for our registered labels for the taxonomy.
 *
 * @since 0.9.0
 * @since 1.6.0 Added the `no_terms` (WP 4.3.0), the `items_list_navigation` (WP 4.4.0)
 *              and `items_list labels` (WP 4.4.0) labels.
 */
```
(They should be the correct labels to add as of right now.)

**Comment by tw2113** [comment]
There's likely more we can do with this, but 423-update-unit-test-options is a start.

**Comment by tw2113** [comment]
Manually merged in to `release1140` branch
