### ISSUE TITLE
Undefined index used in custom-post-type-ui.php

### ISSUE THREAD

**Issue by jigawot** [WebDevStudios/custom-post-type-ui#487]
We'd like to run with WP_DEBUG set to true to identify potential problems, but this plugin uses an undefined index in a few places:

Notice: Undefined index: rewrite_withfront in /var/www/html/web/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 471
...

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/custom-post-type-ui/issues/275

**Comment by tw2113** [comment]
Known issue that I'm not presently able to get around with 100% success rate, due to how the previous settings were stored. Re-saving your post types, after an upgrade, should fill in the indexes and remove the notice.

**Comment by jigawot** [comment]
Can you use an isset() to suppress the warning?

**Comment by tw2113** [comment]
Tried. Explanation from me in that other issue:

And they are not hurting anything nor will they interfere with the functionality, but it's something i'm having to do since empty( '0' ) evaluates to true, and '0' is one of the values possibly stored in the old settings. New settings store 'true' or 'false' which is less of an issue with the conversion.

Re-saving should fill in the values with the 'true' and 'false' keywords, preventing the issue from showing up now.

**Comment by jigawot** [comment]
Okay.  Sorry for the duplicate issue.

**Comment by tw2113** [comment]
Not a problem, we get this one every now and then. I'm just wishing everyone would get upgraded past 1.0.0 so I could start preventing the notice again.

**Comment by jigawot** [comment]
Sorry, I inherited an old project and was doing just that: upgrading.
