### ISSUE TITLE
I fail to add an endpoint

### ISSUE THREAD

**Issue by mihdan** [WebDevStudios/custom-post-type-ui#512]
Hi!

I fail to add an endpoint (using add_rewrite_endpoint) for custom post type, created with your plugin CPTUI.

My code:

```php
function roomble_init() {
   add_rewrite_endpoint( 'test', EP_ALL );
   //flush_rewrite_rules();
}
add_action( 'init', 'roomble_init' );

add_filter( 'cptui_pre_register_post_type', function( $args ) {
   $args['rewrite']['ep_mask'] = EP_ALL;

   return $args;
},10 );
```
It doesn’t work - 404 error page http://site.com/my_custom_post_type/test/bar/

**Comment by tw2113** [comment]
Can you please start a forum support request over at http://wordpress.org/support/plugin/custom-post-type-ui for this, since it's not a direct issue with the plugin itself. Please provide info on the following questions in that thread as well.

Also when you do, could you provide any resources you've been using to try and solve this? Are you sure that that's the intended url structure as well? the "my_custom_post_type" portion seems like what you'd want to have the "test" part in, but I don't know your intents at the moment either.

Thanks
