### ISSUE TITLE
CPT Title not translatable in WPML

### ISSUE THREAD

**Issue by Battleheart** [WebDevStudios/custom-post-type-ui#587]
Hi there,
I'm new to the plugin. I'm using it because I read online that it's compatible with WPML.

It works as expected exception made of translation capability.

There seems to be an issue. I can't find a way to translate my CPTs titles. WPML says since the original string isn't hardcoded, it can't be translated.

Am I missing something? How can I do it?

Thanks for your time.

**Comment by tw2113** [comment]
Which title are you referring to? The title for an individual post in the post type? Or something from one of our plugin's settings pages?

In terms of the stuff that WPML focuses on, technically CPTUI is compatible, because we simply register the post types and taxonomies and let WP core handle the rest, just as if you wrote your own code to register it.

However, if you're wanting to internationalize the labels you enter, with WPML, then we don't really have a solid WPML-compatible setup, due to the fact that we save those provided label values, as is, to the database. We have ideas, but nothing done, to try and help make the labels and whatnot l10n ready for multi-language sites.

Let me know if I'm way off track or not here.

**Comment by tw2113** [comment]
Closing as an issue. We can continue discussion despite that closed status.
