### ISSUE TITLE
Multiple fields in a custom field is not working properly.

### ISSUE THREAD

**Issue by nisan92** [WebDevStudios/custom-post-type-ui#604]
I am trying to create a repeatable custom field which is consist of 4 different fields like date, start time, end time, city.
the problem is when i add the type text_date or text_time, time-picker and date-picker not working. I need to fix that .

Also another problem the data i am inserting is not retrieving , it just return a string which i need to be an array.

Please see the screenshot  http://prntscr.com/ece0yd . Is there any fix for this.

**Comment by tw2113** [comment]
@nisan92 are you sure this is meant for the Custom Post Type UI repo/issue list? Feels like it's more [CMB2](http://github.com/WebDevStudios/CMB2/)

If you know you're in the right place, then I'm not sure what to suggest, since CPTUI doesn't do anything with customizing/custom meta boxes.

**Comment by nisan92** [comment]
Well first thing here is nothing about CPTUI , My question is all about CMB2 .  What i am trying to create a custom field type which will be repeatable and which will contain 4 different fields. I already create that field type But the problem is after saving data it retrieve only first element of that array.   

So what i need to know is how can i retrieve other values.

please check these 2 images bellow, first one is before saving , and second one is after saving 
http://prntscr.com/egjneh
http://prntscr.com/egjo19

**Comment by tw2113** [comment]
Since it's about CMB2, I'd recommend posting a thread at https://wordpress.org/support/plugin/cmb2 and we'll see about what can be done there. When the thread is created, re-provide the screenshares, as well as the CMB2 configuration code you're presently using.

The GitHub repo we're posting to right now is the one for CPTUI, which is why I was completely confused by the initial posting. Because of that, going to mark this issue as closed. We can still post if necessary.
