### ISSUE TITLE
CSS is loaded on all admin pages, which can conflict with other plugins.

### ISSUE THREAD

**Issue by Shelob9** [WebDevStudios/custom-post-type-ui#635]
We ran into a problem today with Caldera Forms where CPT UI's .required class was causing required items in our settings to look like a validation error had happened. 

Would a PR to add conditional logic to `cptui_add_styles()` be welcome?

Related: https://github.com/CalderaWP/Caldera-Forms/issues/1784

**Comment by tw2113** [comment]
Hmm, thanks for pointing this out. I'm looking at taking care of this with a bugfix release. I have #634 that I want to get fixed as well, and I can slip this in too. I'm thinking more about getting my CSS selectors more specific for our code rather than conditional loading of the CSS. That said, both methods are valid solutions.

**Comment by Shelob9** [comment]
@tw2113 I think both would be a good idea. Both of us should prefix out use of `.required` class.

**Comment by Shelob9** [comment]
@tw2113 Delayed thanks for this fix!

**Comment by tw2113** [comment]
Welcome, Josh.
