### ISSUE TITLE
PHP notices/warnings.

### ISSUE THREAD

**Issue by AndreCapelache** [WebDevStudios/custom-post-type-ui#642]
Hi, when execute the plugin in PHP 7.1 I receive this errors:

Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332

Notice: Undefined index: has_archive in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 355

Notice: Undefined index: capability_type in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 426

Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 433

Notice: Undefined index: taxonomies in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 434

Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332

Notice: Undefined index: has_archive in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 355

Notice: Undefined index: capability_type in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 426

Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 433

Notice: Undefined index: taxonomies in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 434

Warning: Invalid argument supplied for foreach() in /var/www/html/src/wp-includes/class-wp-post-type.php on line 634

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php:332) in /var/www/html/src/wp-includes/pluggable.php on line 1210

**Comment by tw2113** [comment]
Hey @AndreCapelache Nothing really specific to PHP7.1 here. Feels more like a number of places in the saved options/current data isn't necessarily potentially existent.

Have you recently updated from a really old version of the plugin? Perhaps a case of hadn't touched the post types option in a long time and finally had reason to update something?

Am noting down where from the output above, we can get some extra checks in to prevent the notices and warnings from showing up.

**Comment by AndreCapelache** [comment]
Hi @tw2113. 

I didn't update the plugin. I only changed the php version, from Apache with PHP 5.6 to Nginx+FPM with PHP 7.1  and changed the folder path to the new server.

Very thanks

**Comment by tw2113** [comment]
Noted. Best guess I have for the suddenness then is increased error reporting due to the version switch.

If possible hit save on all related post types for your current CPTUI setup, and it should help clear out the errors.

I have the following noted down for better value checking:

Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332
Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 332
Notice: Undefined index: has_archive in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 355
Notice: Undefined index: capability_type in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 426
Notice: Undefined index: supports in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 433
Notice: Undefined index: taxonomies in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 434

**Comment by AndreCapelache** [comment]
Yes, I save again all the post types and the notices is gone.

Very thanks

**Comment by tw2113** [comment]
Master branch has all but Notice: Undefined index: taxonomies in /var/www/html/src/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 434 at the moment.

**Comment by AndreCapelache** [comment]
Perfect, Very thanks!!!

**Comment by tw2113** [comment]
Not closing as "won't fix" but am closing as we'd need to have a fresh version to match current line numbers.
