### ISSUE TITLE
Could menu icons be expanded to custom icon libraries?

### ISSUE THREAD

**Issue by chrisblakley** [WebDevStudios/custom-post-type-ui#647]
My thought is that maybe the Menu Icon field could accept _any_ class names so that it could support custom font libraries such as Font Awesome. CPT UI would not need to load any additional libraries.

Right now if I type in non-Dashicon classes it is detected as a URL.

I'm happy with the Dashicons, but doing something like this could allow for a ton more customization if a certain custom post type needed it.

**Comment by tw2113** [comment]
Definitely a nice thought, but I have to believe it would be outside the scope of what our plugin is set up to handle. How the values are handled is all internal to how WordPress registers post types. So it's Core that determine how to output in the menu. It must have something internal that determines what values are a valid Dashicon, and acts accordingly.

No idea if they have any sort of filters in that spot, but I'm also hesitant to say they would since I know the admin menu isn't the prettiest thing ever, and giving some control to users beyond dashicons/simple urls to images would be prone to headache.

Going to leave open for a little bit in case someone happens to have more information that could be useful.

Only alternative that i can think of, for what it's worth, would be perhaps using javascript to target and switch classes on your own.

**Comment by chrisblakley** [comment]
Ah, thanks for the info- a JS solution would probably work, but I think for the sake of simplicity it'd be better to just stick with Dashicons.

**Comment by ptrkcsk** [comment]
My plugin [FA WP Admin Menu Icons](https://wordpress.org/plugins/fa-wp-admin-menu-icons/) works well with CPT UI. You can simply enter the Font Awesome class into the 'Menu Icon' field:

![screenshot 2017-12-24 15 27 14](https://user-images.githubusercontent.com/4766244/34329706-f4a3b3a0-e8be-11e7-9627-e3d6b7ddf246.png)
