### ISSUE TITLE
Reveal select button for post type/taxonomy if js execution breaks during page load

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#653]
Right now we hide for js-enabled users but display for no-js users. Possible to reveal for those who have broken js involved in page load?

**Comment by Hube2** [comment]
Just wanted to add a message about why I figured this out. I run an apache server right on my laptop that I do development on. With this setup I can basically do dev and testing even when I have no internet access available. 

It was at one of these times when I noticed this. I actually created a bit of a mess because I selected a post type and then went about editing it, not realizing the page had not refreshed, saved and then figured out I edited the wrong one. 

I realize that this not a normal setup, and this is more of a problem for me than it is for you. It is because of this that all of the sites that I build have a fallback local script if for some reason the remote script can't be loaded. One of those interesting things I have to deal with because I live out in the sticks without 100% reliable internet access.

I can completely understand if this is a low priority issue.

**Comment by tw2113** [comment]
For what it's worth, I do consider it a very worthy UX issue to resolve, and it most definitely can potentially affect everyone, local development or live site. So we most definitely plan to address it the best we can, but need to figure out how :D Also CPTUI as a whole is in a pretty good stable place, so we've let development simmer at the moment. Hoping to get things ramped up some more in the near future.

**Comment by tw2113** [comment]
Remove hiding button from `.js` selector in CSS and hide via JavaScript instead.

```
$('#cptui_select_post_type_submit').hide();
$('#cptui_select_taxonomy_submit').hide();
```

Should probably have separate from our main JS file, and loaded really late because any errors that occur AFTER our loading, would still result in a hidden button and a broken page.

**Comment by tw2113** [comment]
Going to try as part of our main JS file. We can re-visit in the future if this still doesn't prove enough, and it hasn't been a widespread issue as a whole. If it becomes more prominent, we care-address.

Changes have been pushed up into release158 branch.
