### ISSUE TITLE
Add field for show_in_graphql

### ISSUE THREAD

**Issue by paulisloud** [WebDevStudios/custom-post-type-ui#740]
WP GraphQL looks for the following fields in custom post types in order for custom post types and taxonomies to be queryable via graphql:

```
  'show_in_graphql' => true,
  'graphql_single_name' => 'book',
  'graphql_plural_name' => 'books',
```

Would you be interested in a pull request to add this as a field to CPT UI?

**Comment by tw2113** [comment]
Honestly the first time I've seen anyone express interest in any sort of WPGraphQL integration with CPTUI, so I can't say it's a detail in high demand.

At least until there is more, I'm more inclined to lean towards some quick documentation about the following two hooks that can just as easily be used to insert the values.

https://github.com/WebDevStudios/custom-post-type-ui/blob/1.6.1/custom-post-type-ui.php#L471-L481
https://github.com/WebDevStudios/custom-post-type-ui/blob/1.6.1/custom-post-type-ui.php#L642-L654

Alternatively, if you wanted to do up your own plugin that extends CPTUI and still provides UI instead of being a code only solution, we have the hooks available. An example can be seen at https://github.com/tw2113/custom-post-type-ui-capabilities where i've personally done some attempts to provide capabilities UI.

It'll show some examples of adding the UI to the page, what to do for saving, whether it be to the original options CPTUI uses, or your own just for some extra separation, and then inserting into the arguments.

**Comment by paulisloud** [comment]
Looks like those documenation resources should do the trick, thanks for providing those.

**Comment by tw2113** [comment]
Welcome.
