### ISSUE TITLE
What's better workflow to sync local changes with git teams/production server?

### ISSUE THREAD

**Issue by diegosomar** [WebDevStudios/custom-post-type-ui#781]
When we create or update custom post types/custom taxonomies, we need to share this database changes with other people in the team with git AND the production server.

Currently, we save the json in a file and the people which receives the git pull, installs manually in your local WP installation. When we send to production server, we do the same, accessing production WP installation and update manually the custom post types.

But, there's a way to make this automatically?
My first idea is to save the JSON file and creates a WP scheduled task (like WooCommerce does).
In this task, the CPTUI json file is **uploaded** to database.

But the problem is with **upload** part: How to programmatically updates the CPTUI post types and taxonomies via a file save in theme folder?

**Comment by tw2113** [comment]
Hi @diegosomar 

At least for version controlling and having settings changes written to file, I know I have this tutorial typed up https://docs.pluginize.com/article/84-save-cptui-settings-data-to-file

It's not going to handle the committing/deployment part, but at least whenever you save, the settings go to a version controlled file.

Another thing it won't handle is the importing into the db, and I don't have any handy tutorial thought up or available to handle that aspect. It'd be interesting to see. It does have me wondering how easy it'd be to read the file and load from that like ACF Pro does. However, I'd also want to be careful with that because that's a file read every page load, which may be worse than loading a couple options.

None of this covers the detail of syncing post type/taxonomy database content either, in case that was on your radar.

**Comment by diegosomar** [comment]
Hello @tw2113, tks! It's great to save the settings file.
I agree with you, if the plugin had a way to sync (like ACF - free version does it too) will be great.
But, to have a file settings save in the theme folder is a big help! Tks!

**Comment by tw2113** [comment]
Glad we could already have things in place for at least part of your needs :D
