### ISSUE TITLE
Auto-Populate labels only runs on the first click

### ISSUE THREAD

**Issue by brandondove** [WebDevStudios/custom-post-type-ui#811]
I typed in the post slug, singular, and plural labels at the top and clicked the link to populate all of the labels only to realize I typed "Boom" instead of "Book". I tried fixing my spelling error at the top and clicking the link again, but nothing updated because the script to populate the fields checks for values before overwriting. While I do appreciate that it doesn't overwrite any customizations I may have made by hand, I wasn't given any indication as to why it didn't work and ended up having to refresh the page and try again.

I could think of a couple of options here to address this issue.
- There could be a find/replace on the singular/plural values in those fields if there was already something in the label fields.
- There could be a message/alert along with a highlight on fields that had values that couldn't be overwritten indicating that updates weren't made to those fields.

**Comment by tw2113** [comment]
Thanks for this feedback Brandon, and definitely some things to consider here. Not quite sure how I am going to want to proceed just yet, but I will definitely keep this open for pondering on possible solutions.

Will see what may come of it.

**Comment by tw2113** [comment]
Thinking about this one a bit tonight. The problem with find/replace on existing labels is going to be tracking the previous slug/singular/plural variations and then also getting the new version and accurately replacing. Not completely sure I like the second idea because i feel like it'd be all of them each time.

That said @brandondove what do you think of changing this to creating a link to reset the label fields instead? Just empty them all out and let the user start over without refreshing the page?

**Comment by tw2113** [comment]
Going with the clearout idea for the time being. Handled in da18a374839530e9c11f45b7c08d251c66a82b79 and 033d9e3ce87ca002bfd27a88844f73294450c72b
