### ISSUE TITLE
command line interface `wp cptui import` was not working

### ISSUE THREAD

**Issue by enabledbrain** [WebDevStudios/custom-post-type-ui#866]
Hi !

When I do the import, the process shows a successful completion message, but the information in the wp_options table has been registered as a string, which is a serious error in the wordpress ui.

It seems to be caused by $json not being decoded in the import function in wp-cli.php.

Thanks

**Comment by tw2113** [comment]
Thanks for reporting this. Will test it out a bit soon and see about any fixes needing added.

By chance, do you happen to know when the last time it did work? It'd help isolate what releases to check on for broken functionality.

**Comment by enabledbrain** [comment]
I just recently started using it, so I don't know when it started not working properly.
I'm sorry I can't help you.

**Comment by tw2113** [comment]
Confirmed ability to recreate and have fixes found as well.

If you need the fixes asap, let me know and I can let you know what details to change, otherwise, I'll aim for a 1.12.1 release sometime soon. We don't get a huge amount of WP-CLI usage from what I've seen, so I'm not considering this an urgent bug needing fixed today.

**Comment by tw2113** [comment]
Fixed in 1.12.1 release
