### ISSUE TITLE
How to add custom field to the rest API?

### ISSUE THREAD

**Issue by lesleyxyz** [WebDevStudios/custom-post-type-ui#912]
I have the custom post type "Products" which we want to use a "custom field" called "price".
However, when calling the API at `/wp-json/wp/v2/products` I don't see the "price" field.
Can I configure this so it is shown using this plugin?

If I understand it correctly, in the plugin it would need to call the `register_rest_field()` function.

**Comment by tw2113** [comment]
Hi @lesleyxyz I think this may be a good quick tutorial: https://upokary.com/how-to-add-custom-fields-to-rest-api-response-wordpress/

This is going to be something best done on your end since we have no easy way to know exactly what post type slugs you're actually registering, as well as which custom fields you'd want to be adding.

**Comment by lesleyxyz** [comment]
Okay no problem, thanks for the link! I'll try it out!

**Comment by tw2113** [comment]
Welcome.
