### ISSUE TITLE
Ajax requests going nowhere while toggling panels

### ISSUE THREAD

**Issue by aslamatwebdevstudios** [WebDevStudios/custom-post-type-ui#940]
While toggling panels, there are ajax requests generated by the `postbox` js enqueued with the plugin. Below is the code that attaches some ajax requests when the panels are toggled.

https://github.com/WebDevStudios/custom-post-type-ui/blob/3081f9deed0e1dc6337952869d85f3e75014e7b4/src/js/cptui-scripts.js#L4

As these requests have no ajax handler code, it is throwing `403 Forbidden` errors every time we toggle the panel

### Solutions

1. We can add empty ajax request handler php code in the plugin so there will be no 403 error.
2. Another solution is to unbind the postbox toggle js as [mentioned here](https://wordpress.stackexchange.com/questions/39723/unbind-postbox-click-handler) and then add our own jquery toggle code. So there will be no ajax request here.

**Comment by ramsesdelr** [comment]
I found the issue:
There's a [native ajax action](https://github.com/WordPress/WordPress/blob/29d0198455ee7742c5c3c0c0289161487c16738f/wp-admin/includes/ajax-actions.php#L1785) that looks for a nonce inside the post boxes,  and our custom post boxes don't have that propertie.

The purpose of this ajax request is to save the current panel state (open, closed) on the database. 
In order to fix this, we need to:
1. Add a nonce field to the `postboxes` forms.
2. Add id attributes to each of the postbox containers so it can identify which post boxes should be kept opened/closed.

I'll work on this a send a Pull request.
CC @tw2113

**Comment by tw2113** [comment]
@ramsesdelr can you make it so that your work with this specific issue doesn't undo or alter how @aslamatwebdevstudios did work with https://github.com/WebDevStudios/custom-post-type-ui/pull/939/files ? It's that PR and whatnot that brought about this issue that we opened. So whatever we can do to merge, so to speak, would be best.

**Comment by tw2113** [comment]
Fixed in https://github.com/WebDevStudios/custom-post-type-ui/pull/947
